[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Creating a Positive Change Narrative Through Communication Strategies: Framing Change as an Opportunity for Growth"
